import Vue from 'vue'
import { 
    Avatar,
    Button,
    Backtop,
    ButtonGroup,
    Dropdown,
    DropdownMenu,
    DropdownItem,
    Card,
    Container,
    Header,
    Input,
    Loading,
    Main,
    Footer,
    Row,
    Drawer,
    Col,
    Progress,
    Radio,
    RadioButton,
    RadioGroup,
    Menu,
    MenuItem,
    MenuItemGroup,
    Table,
    TableColumn,
    DatePicker,
    Form,
    FormItem,
    Select,
    Submenu,
    Option,
    Link,
    Notification,
    Popover
    
} from 'element-ui'
Vue.prototype.$notify = Notification;
Vue.use(Avatar)
Vue.use(Button)
Vue.use(Backtop)
Vue.use(ButtonGroup)
Vue.use(Dropdown)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(Card)
Vue.use(Container)
Vue.use(Input)
Vue.use(Loading)
Vue.use(Header)
Vue.use(Main)
Vue.use(Footer)
Vue.use(Row)
Vue.use(Drawer)
Vue.use(Col)
Vue.use(Progress)
Vue.use(Radio)
Vue.use(RadioButton)
Vue.use(RadioGroup)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(MenuItemGroup)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(DatePicker)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Select)
Vue.use(Submenu)
Vue.use(Option)
Vue.use(Link)
Vue.use(Popover)
